server:
  port: 9004
spring:
  application:
    name: nacos-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8082
management:
  endpoints:
    web:
      exposure:
        include: "*"