server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  cloud:
    #consul注册中心地址
    consul:
      host: 192.168.1.24
      port: 8500
      discovery:
        service-name: ${spring.application.name}