server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8082
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
service-url:
  nacos-user-service: http://nacos-provider-payment


#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true
