server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      bindings:
        #这个名字是一个通道的名称
        output:
          #表示要使用的exchange名称定义
          destination: studyExchange
          #本次为json 文本则设置成"text/plain"
          content-type: application/json
          binder: local_rabbit
      #在此处配置要绑定的rabbit的服务信息
      binders:
        #表示定义的名称，用于rabbitmq的整合
        local_rabbit:
          type: rabbit  #消息组件类型
          environment:
            rabbitmq:
              host: localhost
              port: 5672
              username: guest
              password: guest
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: send-8801.com
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

