server:
  port: 80
spring:
  application:
    name: cloud-consumer-feign-hystrix-order
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    fetch-registry: true


feign:
  hystrix:
    #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
    enabled: true
ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 3000
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 3000


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000



